In [20]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2
# 多行输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## 测试结果的正确性

In [21]:
import pandas as pd
import numpy as np
from pathlib import Path

In [22]:
root = Path('../')

### baseline

In [23]:
baseline = pd.read_csv(root/'submission_phi.csv', header=None)

In [24]:
ret1 = baseline[1].values
ret1

array([3.0302, 3.1187, 4.2483, ..., 3.6622, 3.1527, 2.7529])

### new ret

In [60]:
# sub1 = pd.read_csv(root/'Sun-May-19-19:17:36-2019_submission.csv', header=None) # 有效 xDeepFM 
sub1 = pd.read_csv(root/'Wed-May-22-18:59:55-2019_submission.csv', header=None) # 无效

In [61]:
ret = sub1[1].values
ret

array([8.4779, 7.3563, 2.0175, ..., 5.5723, 9.011 , 8.7802])

In [62]:
np.allclose(ret1, ret, atol=1e-02)

False

In [63]:
max(abs(ret1 - ret))

inf

In [47]:
cnt = 0
for x in list(abs(ret1 - ret)):
    if x >= 14:
#         print(x)
        cnt += 1
cnt

0

In [48]:
t = np.where(ret < ret1, ret, ret1)

In [49]:
max(abs(ret1 - t))

6.7668

In [50]:
ret.shape, ret1.shape

((38596,), (38596,))

In [51]:
test_b = pd.read_csv('../data/test_set_B.csv')

In [48]:
multi_value_features = [
    'time', 'age', 'area', 'device', 'behavior', 'connectionType', 'gender', 'education', 'status', 'work'
]

In [49]:
for i in multi_value_features:
    print(max([len(str(x).split(',')) for x in test_b[i]]))

7
986
1576
4
221
5
3
6
8
1


In [50]:
test_b.loc[0, 'time']

'281474976710655,281474976710655,281474976710655,281474976710655,281474976710655,281474976710655,281474976710655'

In [51]:
train = pd.read_csv('../data/train_set_final.csv',low_memory=False)

In [52]:
for i in multi_value_features:
    print(max([len(str(x).split(',')) for x in train[i]]))

7
995
1576
6
485
5
1
7
8
5


In [53]:
valid = pd.read_csv('../data/valid_set_final.csv',low_memory=False)

In [54]:
for i in multi_value_features:
    print(max([len(str(x).split(',')) for x in valid[i]]))

7
986
1576
4
268
5
1
7
8
1


In [8]:
ret1

array([3.0302, 3.1187, 4.2483, ..., 3.6622, 3.1527, 2.7529])

In [14]:
ret2 = (ret + ret1)/2

In [18]:
ret2

array([2.9193 , 3.14235, 4.2122 , ..., 3.65205, 2.96215, 2.7193 ])

In [16]:
sub1.iloc[:, 1] = ret2

In [19]:
sub1.to_csv('submission.csv', index=None, header=None, encoding='utf-8')