In [20]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2
# 多行输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## 测试结果的正确性

In [21]:
import pandas as pd
import numpy as np
from pathlib import Path

In [22]:
root = Path('../')

### baseline

In [88]:
baseline = pd.read_csv(root/'submission_phi.csv', header=None)

In [89]:
ret1 = baseline[1].values
ret1

array([3.0302, 3.1187, 4.2483, ..., 3.6622, 3.1527, 2.7529])

### new ret

In [90]:
sub1 = pd.read_csv(root/'Sun-May-19-19:17:36-2019_submission.csv', header=None) # 有效 xDeepFM 
# sub1 = pd.read_csv(root/'Wed-May-22-22:09:19-2019_submission.csv', header=None) # 无效

In [91]:
ret = sub1[1].values
ret

array([2.8084, 3.166 , 4.1761, ..., 3.6419, 2.7716, 2.6857])

In [92]:
np.allclose(ret1, ret, atol=1e-02)

False

In [93]:
max(abs(ret1 - ret))

1.3334

In [94]:
cnt = 0
for x in list(abs(ret1 - ret)):
    if x >= 14:
#         print(x)
        cnt += 1
cnt

0

In [95]:
t = np.where(ret > ret1, ret, ret1)

In [96]:
max(abs(ret1 - t))

0.9964

In [97]:
ret.shape, ret1.shape

((38596,), (38596,))

In [98]:
test_b = pd.read_csv('../data/test_set_B.csv')

In [99]:
multi_value_features = [
    'time', 'age', 'area', 'device', 'behavior', 'connectionType', 'gender', 'education', 'status', 'work'
]

In [100]:
for i in multi_value_features:
    print(max([len(str(x).split(',')) for x in test_b[i]]))

7
986
1576
4
221
5
3
6
8
1


In [101]:
test_b.loc[0, 'time']

'281474976710655,281474976710655,281474976710655,281474976710655,281474976710655,281474976710655,281474976710655'

In [51]:
train = pd.read_csv('../data/train_set_final.csv',low_memory=False)

In [52]:
for i in multi_value_features:
    print(max([len(str(x).split(',')) for x in train[i]]))

7
995
1576
6
485
5
1
7
8
5


In [53]:
valid = pd.read_csv('../data/valid_set_final.csv',low_memory=False)

In [54]:
for i in multi_value_features:
    print(max([len(str(x).split(',')) for x in valid[i]]))

7
986
1576
4
268
5
1
7
8
1


In [8]:
ret1

array([3.0302, 3.1187, 4.2483, ..., 3.6622, 3.1527, 2.7529])

In [14]:
ret2 = (ret + ret1)/2

In [18]:
ret2

array([2.9193 , 3.14235, 4.2122 , ..., 3.65205, 2.96215, 2.7193 ])

In [16]:
sub1.iloc[:, 1] = ret2

In [19]:
sub1.to_csv('submission.csv', index=None, header=None, encoding='utf-8')

In [102]:
t

array([3.0302, 3.166 , 4.2483, ..., 3.6622, 3.1527, 2.7529])

In [103]:
sub1.iloc[:, 1] = t

In [104]:
sub1

0       1
0          1  3.0302
1          2  3.1660
2          3  4.2483
3          4  2.6328
4          5  2.4608
5          6  3.1269
6          7  1.7714
7          8  2.4207
8          9  3.3631
9         10  6.7720
10        11  4.7214
11        12  4.3722
12        13  2.3653
13        14  2.9546
14        15  2.4529
15        16  3.9662
16        17  3.7313
17        18  4.2726
18        19  3.4479
19        20  3.7131
20        21  4.0332
21        22  4.0779
22        23  2.8655
23        24  3.9357
24        25  3.3988
25        26  4.0703
26        27  3.6060
27        28  4.1142
28        29  3.1663
29        30  2.4264
...      ...     ...
38566  38567  4.6747
38567  38568  2.7937
38568  38569  4.2203
38569  38570  4.0545
38570  38571  4.4530
38571  38572  2.0135
38572  38573  6.0633
38573  38574  2.7795
38574  38575  3.7453
38575  38576  2.8261
38576  38577  4.7976
38577  38578  2.5221
38578  38579  4.4302
38579  38580  3.2081
38580  38581  4.4385
38581  38582  3.1370
38582  38583  4.3114
38583  38584  4.1571
38584  38585  3.3469
38585  38586  3.3771
38586  38587  6.7715
38587  38588  1.8587
38588  38589  2.7066
38589  38590  3.8528
38590  38591  3.2450
38591  38592  2.4432
38592  38593  2.5866
38593  38594  3.6622
38594  38595  3.1527
38595  38596  2.7529

[38596 rows x 2 columns]

In [105]:
sub1.to_csv('submissionx.csv', index=None, header=None, encoding='utf-8')