In [5]:
import pandas as pd
import torch
from torch import nn
from sklearn.feature_extraction.text import CountVectorizer

In [68]:
data = pd.read_csv('test_set_B.csv')

In [69]:
data.head()

sample_id   ad_id  ad_type_id  ad_account_id  item_id  item_type  size  \
0          1  152978         118          23511       -1          3    30   
1          2  507977         122           4211      629         13    30   
2          3  639943          84          15582     2525         13    34   
3          4  605859          98          10907     3808         13    40   
4          5  742582         122          15855     7017         13    40   

   is_all_field  has_product_id  has_price  ... crt_dateDayofweek  \
0         False           False      False  ...                 1   
1          True            True      False  ...                 1   
2         False            True      False  ...                 3   
3          True            True      False  ...                 3   
4         False            True      False  ...                 3   

  crt_dateDayofyear crt_dateIs_month_end crt_dateIs_month_start  \
0               334                False                  False   
1                64                False                  False   
2               172                False                  False   
3                80                False                  False   
4                59                 True                  False   

  crt_dateIs_quarter_end crt_dateIs_quarter_start crt_dateIs_year_end  \
0                  False                    False               False   
1                  False                    False               False   
2                  False                    False               False   
3                  False                    False               False   
4                  False                    False               False   

  crt_dateIs_year_start crt_dateHour crt_dateElapsed  
0                 False            2      1480387159  
1                 False           13      1551793928  
2                 False            7      1529565757  
3                 False            9      1553161934  
4                 False            4      1551329520  

[5 rows x 36 columns]

In [70]:
data['age'].head()

0    182,202,739,340,536,287,690,988,187,367,479,94...
1                                                   -9
2    433,202,739,340,988,479,942,731,844,837,333,40...
3                                                   -9
4                   433,819,79,522,601,753,347,829,741
Name: age, dtype: object

In [71]:
data['age'] = data['age'].astype('object')

In [74]:
data['age'].replace({'-999': 'unk', '-9': 'all'}, inplace=True)

In [75]:
data['age'].head()

0    182,202,739,340,536,287,690,988,187,367,479,94...
1                                                  all
2    433,202,739,340,988,479,942,731,844,837,333,40...
3                                                  all
4                   433,819,79,522,601,753,347,829,741
Name: age, dtype: object

In [76]:
cv = CountVectorizer()

In [77]:
hot = cv.fit_transform(data['age']).toarray()

In [78]:
hot.shape

(38596, 993)

In [79]:
hot

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]], dtype=int64)

In [82]:
t = set.union(*[set(i.split(',')) for i in data['age']])

In [83]:
len(t)

1002

In [84]:
sorted(cv.get_feature_names())[-10:]

['992', '993', '994', '995', '996', '997', '998', '999', 'all', 'unk']

In [85]:
t - set(cv.get_feature_names())

{'1', '2', '3', '4', '5', '6', '7', '8', '9'}

In [86]:
ebb = nn.EmbeddingBag(993, 10)
eb = nn.Embedding(993, 10)

In [91]:
out1 = ebb(torch.LongTensor(hot))
out1

tensor([[ 0.2780, -1.4996, -1.0239,  ..., -0.6200, -0.6794,  0.5832],
        [ 0.3323, -1.5744, -1.0652,  ..., -0.6533, -0.7629,  0.6060],
        [ 0.2873, -1.5124, -1.0310,  ..., -0.6257, -0.6937,  0.5871],
        ...,
        [ 0.3323, -1.5744, -1.0652,  ..., -0.6533, -0.7629,  0.6060],
        [ 0.3106, -1.5445, -1.0487,  ..., -0.6400, -0.7295,  0.5969],
        [ 0.3323, -1.5744, -1.0652,  ..., -0.6533, -0.7629,  0.6060]],
       grad_fn=<EmbeddingBagBackward>)

In [92]:
out1.shape

torch.Size([38596, 10])

In [93]:
out2 = eb(torch.LongTensor(hot))
out2

tensor([[[-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467],
         [-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467],
         [-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467],
         ...,
         [-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467],
         [-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467],
         [-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467]],

        [[-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467],
         [-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467],
         [-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467],
         ...,
         [-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467],
         [-1.7149,  0.5675,  0.1259,  ...,  0.9270,  0.0234, -1.4817],
         [-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467]],

        [[-0.5017,  0.2927, -0.7549,  ..., -0.0204, -0.7708,  0.3467],
         [-0.5017,  0.2927, -0.7549,  ..., -0

In [94]:
out2.shape

torch.Size([38596, 993, 10])

In [100]:
out3 = torch.mean(out2, dim=1)
out3

tensor([[-0.5457,  0.3027, -0.7230,  ...,  0.0139, -0.7420,  0.2804],
        [-0.5029,  0.2930, -0.7541,  ..., -0.0195, -0.7700,  0.3449],
        [-0.5383,  0.3010, -0.7283,  ...,  0.0082, -0.7468,  0.2915],
        ...,
        [-0.5029,  0.2930, -0.7541,  ..., -0.0195, -0.7700,  0.3449],
        [-0.5200,  0.2969, -0.7416,  ..., -0.0061, -0.7588,  0.3191],
        [-0.5029,  0.2930, -0.7541,  ..., -0.0195, -0.7700,  0.3449]],
       grad_fn=<MeanBackward0>)

In [101]:
out3.shape

torch.Size([38596, 10])